---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
data <- read.table(unz("activity.zip", "activity.csv"), header=TRUE, sep=",")
```
## What is mean total number of steps taken per day?
Daily Total Number of Steps taken Daily are...
```{r}
sum_table <- aggregate(steps ~ date, data = data, sum )
hist(sum_table$steps, col = "blue", main = "Total Steps Taken Daily", ylab = "Percentage", xlab = "Total Steps")
```

Mean and Median of steps taken...
```{r}
steps <- sum_table$steps
mean(steps)
median(steps)
```

##What is the average daily activity pattern?

```{r}
# Create frame of average steps for each interval
averages <- aggregate(steps ~ interval, data, mean)

# plot averages frame
plot(averages, type = "l", main = "Average Steps per Interval", ylab = "Steps", xlab = "Interval")

# Find Interval with highest Average of steps
maxtime <- averages[averages$steps == max(averages$steps),]
maxtime$interval

```

## Imputing missing values

```{r}
# Calculate total number of NA values
sum(is.na(data[,1]))

# reuse average value for each interval and name columns accordingly
names(averages) <- c("avg_interval", "avg_steps")
# replace NA values with average cast as an integer for that time interval in a new dataframe
# as the median seemed to be distorted by the NA entries
newdata_tmp <- cbind(data, averages)
newdata_tmp$steps[is.na(newdata_tmp$steps)] <- as.integer(newdata_tmp$avg_steps[is.na(newdata_tmp$steps)])

newdata <- newdata_tmp[, 1:3]
# Repeat Step 1 with new dataset
new_sum_table <- aggregate(steps ~ date, data = newdata, sum )
hist(new_sum_table$steps, col = "red", main = "New Total Steps Taken Daily", ylab = "Percentage", xlab = "Total Steps")
```

Mean and Median of steps taken in New dataset...
```{r}
new_steps <- new_sum_table$steps
mean(new_steps)
median(new_steps)

```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
#data$intervaltime <- formatC(data$interval, width = 4, format = "d",  flag = 0)

# Then create Timestamp as posix and merge of date and interval
#data$Timestamp <- paste(data$date, data$intervaltime, sep = " ")
#data$Timestamp <- strptime(data$Timestamp, format = "%Y-%m-%d %H%M")

# plot the steps vs newly formed Timestamp
#plot(data$Timestamp, data$steps, type = "l", main = "Daily Activity", ylab = "Steps", xlab = "Date")
```

